name: netstreams-release

on:
  push:
    paths:
      - 'src/**'    
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch

    - uses: actions/checkout@v2

    - uses: fregante/setup-git-user@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - run: npm install
      name: NPM install

    - run: |
        git fetch -p -P
        git checkout ${{ steps.extract_branch.outputs.branch }}
      name: Switch source branch

    - run: git tag -l | xargs git tag -d && git fetch -t
      name: Purge tags

    - run: npm run release
      name: Increment Version

    - run: npm run build
      name: Build

    - run: npm run publish:nuget --api_key=${{ secrets.NUGET_API_KEY }}
      name: Push packages to Nuget

    - run: git push --follow-tags origin ${{ steps.extract_branch.outputs.branch }}
      name: Push tags and release version

