name: pre-release build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fregante/setup-git-user@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - run: npm ci

    - name: Increment pre-release
      if: ${{ github.event_name == 'pull_request' }}
      run: npm run pre-release

    - name: Increment pre-release
      if: ${{ github.event_name == 'push' }}
      run: npm run release

    - run: npm run build
